# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('instrument', models.CharField(choices=[('G', 'Guitar'), ('B', 'Base'), ('D', 'Drums'), ('V', 'Vocals'), ('K', 'Keyboard'), ('O', 'Others')], max_length=1)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
