# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171128_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKeyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activationkey',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.DeleteModel(
            name='ActivationKey',
        ),
        migrations.AddField(
            model_name='activationkeyinfo',
            name='user',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
