# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171128_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instrument',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
