# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171128_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkeyinfo',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
