# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171130_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_liked',
            field=models.IntegerField(default=0),
        ),
    ]
