# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_total_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
