# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171209_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_followings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='num_followers',
            field=models.IntegerField(default=0),
        ),
    ]
