# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171209_2333'),
        ('users', '0010_user_user_type'),
    ]

    operations = [
    ]
