# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20171212_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='static/default-profile.png', upload_to=users.models.profile_image_directory_path),
        ),
    ]
