# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:30
from __future__ import unicode_literals

from django.db import migrations
import users.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20171213_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=users.fields.DefaultStaticImageField(blank=True, upload_to=users.models.profile_image_directory_path),
        ),
    ]
