# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20171214_2303'),
        ('users', '0015_merge_20171213_0949'),
    ]

    operations = [
    ]
