# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20171220_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bg',
            field=models.ImageField(blank=True, upload_to=users.models.profile_bg_directory_path),
        ),
        migrations.AddField(
            model_name='facebookuserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
