# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20171213_0949'),
        ('users', '0018_auto_20171214_0130'),
    ]

    operations = [
    ]
