# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180114_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, choices=[('R', 'Rock'), ('P', 'Pop'), ('H', 'Hiphop'), ('J', 'Jazz'), ('E', 'Electronic'), ('C', 'Classic'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instrument',
            field=models.CharField(blank=True, choices=[('V', 'Vocal'), ('G', 'Guitar'), ('B', 'Bass'), ('D', 'Drums'), ('K', 'Keyboards'), ('O', 'Others')], max_length=1, null=True),
        ),
    ]
