# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_facebookuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuserinfo',
            name='facebook_user_id',
            field=models.CharField(default='98698786565436769', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
