# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180115_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instrument',
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', to='users.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='instrument',
            field=models.ManyToManyField(blank=True, related_name='instrument', to='users.Instrument'),
        ),
    ]
