# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180119_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='user_genre', to='users.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instrument',
            field=models.ManyToManyField(blank=True, related_name='user_instrument', to='users.Instrument'),
        ),
    ]
