# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180119_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_liked',
        ),
    ]
