# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_track', models.FileField(upload_to='comment_tracks')),
                ('instrument', models.CharField(choices=[('G', 'Guitar'), ('B', 'Base'), ('D', 'Drums'), ('V', 'Vocals'), ('K', 'Keyboard'), ('O', 'Others')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instrument', models.CharField(choices=[('G', 'Guitar'), ('B', 'Base'), ('D', 'Drums'), ('V', 'Vocals'), ('K', 'Keyboard'), ('O', 'Others')], max_length=1)),
                ('master_track', models.FileField(upload_to='master_tracks')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commenttrack',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
