# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_track',
            field=models.FileField(default='', upload_to='author_tracks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='master_track',
            field=models.FileField(blank=True, null=True, upload_to='master_tracks'),
        ),
    ]
