# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171127_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrack',
            name='instrument',
            field=models.CharField(choices=[('G', 'Guitar'), ('B', 'Bass'), ('D', 'Drums'), ('V', 'Vocals'), ('K', 'Keyboard'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='commenttrack',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_tracks', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='instrument',
            field=models.CharField(choices=[('G', 'Guitar'), ('B', 'Bass'), ('D', 'Drums'), ('V', 'Vocals'), ('K', 'Keyboard'), ('O', 'Others')], max_length=1),
        ),
    ]
