# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171129_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrack',
            name='comment_track',
            field=models.FileField(max_length=255, upload_to='comment_tracks'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_track',
            field=models.FileField(max_length=255, upload_to='author_tracks'),
        ),
    ]
