# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171203_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='Rock', max_length=100),
            preserve_default=False,
        ),
    ]
