# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171204_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenttrack',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-liked_date']},
        ),
        migrations.RenameField(
            model_name='commenttrack',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
