# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20171204_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_liked',
            field=models.IntegerField(default=0),
        ),
    ]
