# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_num_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_comments',
        ),
    ]
