# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_num_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixed_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.CommentTrack')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='mixed_tracks',
            field=models.ManyToManyField(related_name='mixed_tracks', through='posts.MixedTrack', to='posts.CommentTrack'),
        ),
    ]
