# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_num_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mixed_tracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_tracks', to='posts.CommentTrack'),
        ),
    ]
