# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20171207_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mixed_tracks2',
            field=models.ForeignKey(default='51', on_delete=django.db.models.deletion.CASCADE, related_name='mixed_tracks2', to='posts.CommentTrack'),
            preserve_default=False,
        ),
    ]
