# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_mixed_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mixed_tracks',
        ),
        migrations.AddField(
            model_name='post',
            name='mixed_tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='mixed_tracks', to='posts.CommentTrack'),
        ),
    ]
