# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20171207_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mixed_tracks',
            field=models.ManyToManyField(blank=True, related_name='mixed_tracks', to='posts.CommentTrack'),
        ),
    ]
