# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20171207_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mixed_tracks',
        ),
        migrations.AddField(
            model_name='commenttrack',
            name='mixed_to',
            field=models.ForeignKey(default='51', on_delete=django.db.models.deletion.CASCADE, related_name='mixed_tracks', to='posts.Post'),
            preserve_default=False,
        ),
    ]
