# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20171207_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mixed_tracks',
        ),
        migrations.AddField(
            model_name='post',
            name='mixed_tracks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
