# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20171207_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttrack',
            name='mixed_to',
        ),
        migrations.AddField(
            model_name='commenttrack',
            name='is_mixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mixed_tracks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
