# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20171208_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mixed_tracks',
        ),
        migrations.AddField(
            model_name='commenttrack',
            name='mixed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
