# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20171208_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttrack',
            name='mixed_to',
        ),
    ]
