# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_commenttrack_mixed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttrack',
            name='mixed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mixed_tracks', to='posts.Post'),
        ),
    ]
