# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20171208_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrack',
            name='comment_track',
            field=models.FileField(max_length=255, upload_to=posts.models.comment_track_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_track',
            field=models.FileField(max_length=255, upload_to=posts.models.author_track_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='master_track',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.master_track_directory_path),
        ),
    ]
