# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20171210_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, upload_to=posts.models.post_img_directory_path),
        ),
    ]
