# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bpm',
            field=models.IntegerField(default=0),
        ),
    ]
