# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180119_1950'),
        ('posts', '0027_post_bpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='post_genre', to='users.Genre'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='instrument',
        ),
        migrations.AddField(
            model_name='post',
            name='instrument',
            field=models.ManyToManyField(blank=True, related_name='post_instrument', to='users.Instrument'),
        ),
    ]
