# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180119_1950'),
        ('posts', '0028_auto_20180119_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttrack',
            name='instrument',
        ),
        migrations.AddField(
            model_name='commenttrack',
            name='instrument',
            field=models.ManyToManyField(blank=True, related_name='comment_instrument', to='users.Instrument'),
        ),
    ]
