# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20180121_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_track_waveform_base',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.author_track_waveform_base_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='author_track_waveform_cover',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.author_track_waveform_cover_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='master_waveform_base',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.master_track_waveform_base_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='master_waveform_cover',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.master_track_waveform_cover_directory_path),
        ),
    ]
