# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20180208_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttrack',
            old_name='comment_track_base',
            new_name='comment_track_waveform_base',
        ),
        migrations.RenameField(
            model_name='commenttrack',
            old_name='comment_track_cover',
            new_name='comment_track_waveform_cover',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='master_waveform_base',
            new_name='master_track_waveform_base',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='master_waveform_cover',
            new_name='master_track_waveform_cover',
        ),
    ]
