# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_user_total_liked'),
        ('posts', '0034_auto_20180221_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='instrument',
        ),
        migrations.AddField(
            model_name='post',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_instrument', to='users.Instrument'),
        ),
    ]
