# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_auto_20171221_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inbox_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
