# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.FileField(upload_to='commits/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('track', models.FileField(upload_to='tracks/')),
            ],
        ),
        migrations.AddField(
            model_name='commits',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixer.Post'),
        ),
    ]
