# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commits',
            new_name='Commit',
        ),
    ]
